blank_issues_enabled: false
contact_links:
  - name: Question ou discussion
    url: https://github.com/AnthoDingo/openZPL/discussions
    about: Pour poser une question d'utilisation ou échanger sur le projet.
